manual ecr docker image scanning

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -167,11 +167,43 @@ jobs:
 
       - name: AWS Scan Docker image
         id: docker-scan
-        uses: alexjurkiewicz/ecr-scan-image@v3.0.0
-        with:
-          repository: ${{ env.ECR_NAME }}
-          tag: latest
-          fail_threshold: high
+        run: |
+            aws ecr start-image-scan --repository-name ${{ env.ECR_NAME }} --image-id imageTag=latest
+
+      - name: Wait for ECR Image Scan Results
+        run: |
+          for i in {1..10}; do
+            SCAN_STATUS=$(aws ecr describe-image-scan-findings \
+              --repository-name dl-web-app-ecr \
+              --image-id imageTag=latest \
+              --query 'imageScanStatus.status' \
+              --output text)
+          
+            echo "Current scan status: $SCAN_STATUS"
+          
+            if [ "$SCAN_STATUS" = "COMPLETE" ]; then
+              echo "Scan completed successfully."
+              exit 0
+            elif [ "$SCAN_STATUS" = "FAILED" ]; then
+              echo "Scan failed."
+              exit 1
+            fi
+          
+            echo "Waiting for scan to complete..."
+            sleep 30
+          done
+          
+          echo "Scan did not complete within the expected time."
+          exit 1
+
+      - name: Get ECR Image Scan Findings
+        run: |
+          aws ecr describe-image-scan-findings \
+            --repository-name dl-web-app-ecr \
+            --image-id imageTag=latest \
+            --output json > findings.json
+          
+          cat findings.json
 
       - name: Revoke Runner IP Address
         run: |
